const Products=[{
    "id": 1,
    "name": "Tuf Puf",
    "src": "img/tuf puf.png",
    "feel": "FIRM",
    "budget": "Less than 10,000",
    "offer": 20,
    "size": "single",
    "length": 72,
    "width": 30,
    "thickness": 3,
    "price": 4786,
    "layers":["Jacquard Fabric","PU Foam Quilt","High Density Foam","PU Foam Quilt"]
  },
  {
    "id": 2,
    "name": "Tuf Puf",
    "src": "img/tuf puf.png",
    "feel": "FIRM",
    "budget": "Less than 10,000",
    "offer": 20,
    "size": "single",
    "length": 75,
    "width": 30,
    "thickness": 3,
    "price": 4986,
    "layers":["Jacquard Fabric","PU Foam Quilt","High Density Foam","PU Foam Quilt"]
  },{
    "id": 85,
    "name": "Dura Bond",
    "src": "img/dura bond.png",
    "feel": "FIRM",
    "budget": "Less than 10,000",
    "offer": 20,
    "size": "single",
    "length": 72,
    "width": 30,
    "thickness": 4,
    "price": 6750,
    "layers":["Knitted Fabric","PU Foam Quilt","Super Soft Foam","Rebonded Foam","PU Foam Quilt"]
  },
  {
    "id": 86,
    "name": "Dura Bond",
    "src": "img/dura bond.png",
    "feel": "FIRM",
    "budget": "Less than 10,000",
    "offer": 20,
    "size": "single",
    "length": 75,
    "width": 30,
    "thickness": 4,
    "price": 7031,
    "layers":["Knitted Fabric","PU Foam Quilt","Super Soft Foam","Rebonded Foam","PU Foam Quilt"]
  }];